# Generated by Django 5.2.5 on 2025-09-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='team',
            new_name='team_id',
        ),
    ]
