# Generated by Django 5.2.5 on 2025-09-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_team_teammember_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='team_id',
            new_name='team',
        ),
    ]
